_target_: src.models.autoencoder_module.Autoencoder

loss: 
  _target_: src.models.modules.losses.contperceptual.LPIPSWithDiscriminator
  disc_start: 50001
  kl_weight: 0.000001
  disc_weight: 0.5
  disc_in_channels: ${data.image_channels}

defaults:
  - autoencoderconfig: autoencoder_kl_64x8x8.yaml
  # - autoencoderconfig: autoencoder_kl_16x16x16.yaml

# set embed_dim equal to z_channels of autoencoderconfig
embed_dim: ${model.autoencoderconfig.z_channels}
lr: 4.5e-6
ckpt_path: !!null
colorize_nlabels: !!null
monitor: !!null
