defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - log_image.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/ssim"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False


model_summary:
  max_depth: -1
